In [42]:
import pandas as pd
import numpy as np
import plotly.express as px
import nbformat

In [48]:
df = pd.read_csv("./data/data2025.csv")
df.head()

     연도   국가명  구분       계       적       공
0  2020    가나  입항   774.0   774.0     0.0
1  2020    가봉  입항     9.0     9.0     0.0
2  2020  가이아나  입항    79.0    79.0     0.0
3  2020   감비아  입항    98.0    98.0     0.0
4  2020  과테말라  입항  6007.0  3519.0  2488.0

In [49]:
# 환적만 선택
trans = df[df["구분"] == "환적"]

# 연도별 TOP 10
trans_top10 = (
    trans.sort_values(["연도", "계"],
    ascending=[True, False])
    .groupby("연도")
    .head(10)
)

# 2025년 TOP 10만 선택
trans_top10_2025 = trans_top10[trans_top10["연도"] == 2025]

fig_trans_top10_2025 = px.bar(
    trans_top10_2025,
    x="국가명",
    y="계",
    title="2025년 부산항 환적 물동량 TOP 10 국가"
)

fig.show(renderer="browser")

In [56]:
# 입항만 선택
arrival = df[df["구분"] == "입항"]

# 연도별 TOP 10
arrival_top10 = (
    arrival.sort_values(["연도", "계"],
    ascending=[True, False]).groupby("연도").head(10)
)

# 2025년 TOP 10만 선택
arrival_top10_2025 = arrival_top10[arrival_top10["연도"] == 2025]

fig_arrival_top10_2025 = px.bar(
    arrival_top10_2025,
    x="국가명",
    y="계",
    title="2025년 부산항 입항 물동량 TOP 10 국가"
)

fig_arrival_top10_2025.show(renderer="browser")

In [55]:
arrival_top10_2025

        연도  국가명  구분           계           적          공
2602  2025   중국  입항  1270019.00  1126943.25  143075.75
2536  2025   미국  입항   873331.50   420298.00  453033.50
2598  2025   일본  입항   781873.00   229198.00  552675.00
2546  2025  베트남  입항   181919.00   152081.00   29838.00
2646  2025   호주  입항   159320.00    72567.00   86753.00
2610  2025  캐나다  입항   125733.50    50573.25   75160.25
2529  2025  멕시코  입항   112828.25    31101.00   81727.25
2518  2025  러시아  입항   111517.00    23705.00   87812.00
2596  2025   인도  입항   108558.25    73301.75   35256.50
2623  2025   태국  입항    94107.00    89979.00    4128.00